services:
  development-rw_back:
    container_name: development-rw_back
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .env
    ports:
      - 4000:4000
    working_dir: /usr/src/back
    command: bash -c "npx prisma generate && npm run dev"
    volumes:
      - .:/usr/src/back
    networks:
      - development-rw_network

networks:
  development-rw_network:
    external: true

